Controllers films users
KamperClout/java-filmorate pull request #6
Opened 2023-07-05 23:03 UTC by KamperClout

2023-07-06 11:29 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний!

Желаю удачи!

2023-07-06 11:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    }
Не очень понятно зачем нужен этот метод

2023-07-06 11:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    }
Не очень понятно зачем нужен этот метод

2023-07-06 11:29 UTC, LexLippi commented on src/test/java/controller/FilmControllerTest.java
> +    }
1. В тестах не нужны модификаторы доступа
2. Точно ли мы перед каждым тестом хотим инициализировать новый контроллер? Кажется, что и одной инициализации хватит

2023-07-06 11:29 UTC, LexLippi commented on src/test/java/controller/UserControllerTest.java
> +public class UserControllerTest {
Аналогичные замечания, как и для `FilmControllerTest`

2023-07-06 16:29 UTC, KamperClout commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    }
То же самое. В тестах использую для проверки изменения размера мапы при update и get

2023-07-06 16:29 UTC, KamperClout commented on src/test/java/controller/FilmControllerTest.java
> +    }
исправил

2023-07-06 16:29 UTC, KamperClout commented on src/test/java/controller/UserControllerTest.java
> +public class UserControllerTest {
исправил

2023-07-07 07:25 UTC, LexLippi approved these changes
Привет!

Отличная работа.

Отписал по поводу метода (на мой взгляд он все равно является лишним).
Если захочешь, то можешь это исправить, либо оставь так, это не критично.

Желаю удачи в следующих спринтах!

2023-07-07 07:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    }
Ок, но для этого же можно использовать метод `findAll`, он возвращает все элементы мапы. Так что если интересует только размер, то вполне достаточно метода, который и так требуют от тебя в ТЗ :)

Более того, в тестах мы работаем как бы со стороны внешнего мира, и нам не важно, как это устроено внутри мапа, файл или СУБД, поэтому надо стараться описывать тесты таким образом, чтобы использовать только публичные методы, которые доступны снаружи.

2023-07-07 12:29 UTC, KamperClout commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    }
все понял!))

2023-07-07 12:36 UTC, merged