sprint 10
KamperClout/java-filmorate pull request #7
Opened 2023-07-12 19:32 UTC by KamperClout

2023-07-13 10:19 UTC, LexLippi requested changes
Привет!

Вообще работу надо присылать только когда все проверки на гитхабе прошли.
В этот раз я ее проверил, она хорошая, всего парочка замечаний, но на будущее это учти!

Желаю удачи!

2023-07-13 10:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Integer> friends;
модификатор доступа

2023-07-13 10:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (Optional.ofNullable(user.getName()).isEmpty() || user.getName().isBlank()) {
А просто `user.getName != null` нельзя?
Зачем такую сложную конструкцию городить

2023-07-13 11:53 UTC, KamperClout commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Integer> friends;
Исправил. По поводу того, что отправил работу с не пройденными проверками на гите.Извиняюсь, просто никак привыкнуть к такому формату сдачи пока не могу)) После 9 спринта подзабыл, что дождаться нужно всех галочек, а тут увидел только что успешно смёржить можно, обрадовался и отправил все сразу. Сейчас увидел что тесты после 28с прервались только, не дождался)))

2023-07-13 13:17 UTC, KamperClout commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (Optional.ofNullable(user.getName()).isEmpty() || user.getName().isBlank()) {
все исправил

2023-07-14 06:45 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-07-16 17:43 UTC, merged